source 'https://github.com/CocoaPods/Specs.git'
platform :ios,"7.0"
pod "AFNetworking"
pod 'JSONKit'
pod 'MagicalRecord'
pod 'RegexKitLite'
pod 'UIColor+FlatColors','~>0.0.2'
pod 'pop','~>1.0.6'
pod "PPiAwesomeButton"
